OrdererOrgs:
  - Name: Orderer
    Domain: middleware-network.com
    Specs:
      - Hostname: orderer
PeerOrgs:
 - Name: weatherdevice
   Domain: weatherdevice.middleware-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: weatherclient
   Domain: weatherclient.middleware-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1