version: '2'

services:

  orderer.middleware-network.com:
    container_name: orderer.middleware-network.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      #- GODEBUG=netdns=go
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/middleware-network.com/orderers/orderer.middleware-network.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/middleware-network.com/orderers/orderer.middleware-network.com/tls/:/var/hyperledger/orderer/tls
    - orderer.middleware-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.weatherdevice.middleware-network.com:
    container_name: peer0.weatherdevice.middleware-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.weatherdevice.middleware-network.com
      - CORE_PEER_ADDRESS=peer0.weatherdevice.middleware-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.weatherdevice.middleware-network.com:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.weatherdevice.middleware-network.com:7055
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.weatherdevice.middleware-network.com:7051
      - CORE_PEER_LOCALMSPID=weatherdeviceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/weatherdevice.middleware-network.com/peers/peer0.weatherdevice.middleware-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/weatherdevice.middleware-network.com/peers/peer0.weatherdevice.middleware-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.weatherdevice.middleware-network.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.weatherdevice.middleware-network.com:
    container_name: peer1.weatherdevice.middleware-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.weatherdevice.middleware-network.com
      - CORE_PEER_ADDRESS=peer1.weatherdevice.middleware-network.com:7055
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7055
      - CORE_PEER_CHAINCODEADDRESS=peer0.weatherdevice.middleware-network.com:7057
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7057
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.weatherdevice.middleware-network.com:7055
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.weatherdevice.middleware-network.com:7051
      - CORE_PEER_LOCALMSPID=weatherdeviceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/weatherdevice.middleware-network.com/peers/peer1.weatherdevice.middleware-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/weatherdevice.middleware-network.com/peers/peer1.weatherdevice.middleware-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.weatherdevice.middleware-network.com:/var/hyperledger/production

    ports:
      - 7055:7055
      - 7057:7057

  peer0.weatherclient.middleware-network.com:
    container_name: peer0.weatherclient.middleware-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.weatherclient.middleware-network.com
      - CORE_PEER_ADDRESS=peer0.weatherclient.middleware-network.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.weatherclient.middleware-network.com:9053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.weatherclient.middleware-network.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.weatherclient.middleware-network.com:9055
      - CORE_PEER_LOCALMSPID=weatherclientMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/weatherclient.middleware-network.com/peers/peer0.weatherclient.middleware-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/weatherclient.middleware-network.com/peers/peer0.weatherclient.middleware-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.weatherclient.middleware-network.com:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9053:9053

  peer1.weatherclient.middleware-network.com:
    container_name: peer1.weatherclient.middleware-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.weatherclient.middleware-network.com
      - CORE_PEER_ADDRESS=peer1.weatherclient.middleware-network.com:9055
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9055
      - CORE_PEER_CHAINCODEADDRESS=peer0.weatherclient.middleware-network.com:9057
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9057
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.weatherclient.middleware-network.com:9055
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.weatherclient.middleware-network.com:9051
      - CORE_PEER_LOCALMSPID=weatherclientMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/weatherclient.middleware-network.com/peers/peer1.weatherclient.middleware-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/weatherclient.middleware-network.com/peers/peer1.weatherclient.middleware-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.weatherclient.middleware-network.com:/var/hyperledger/production
    ports:
      - 9055:9055
      - 9057:9057